#!/bin/sh
# Wrapper to add GNU ReadLine support to fricas. See
# Fricas FAQ:
# 4.1: Clef does not work.  Is there an alternative?

# Note: this script is not intended to be called directly, but is
# called via another script, e.g. fricas

CFILE=$2
RLWRAP=${RLWRAP:=rlwrap}
shift 3
exec $RLWRAP -f $CFILE "$@"
