%% Oh Emacs, this is a -*- Makefile -*-, so give me tabs.
\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/share Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
Files in the share directory are common to all of the system builds.
\end{abstract}
\eject
\tableofcontents
\eject
\section{command.list}
The [[command.list]] file contains command completion strings used by
the [[clef]] command line editor function. In the NAG version this 
lived in the share subdirectory but the open source version moves it
back to the [[lib]] directory where it originally lived.
<<command.list>>=
$(axiom_target_libdir)/command.list: $(srcdir)/algebra/command.list
	$(INSTALL_DATA) $< $@
@

<<*>>=
subdir = src/share/

FILES=$(axiom_target_libdir)/command.list

.SUFFIXES:
.PHONY: all all-share
all: all-ax

all-ax all-share: stamp
	@ echo 3 finished $(srcdir)

stamp: ${FILES}
	-rm -f stamp
	$(STAMP) stamp

mostlyclean-local:
	@-rm -f $(FILES)
	@-rm -f stamp

clean-local: mostlyclean-local
distclean-local: clean-local

<<command.list>>
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
