.TH FRICAS "1" "April 2017" "FriCAS" "User Commands"
.SH NAME
fricas, efricas \- advanced computer algebra system.
.SH SYNOPSIS
.B fricas
[options]
.br
.B efricas

.SH DESCRIPTION
.PP
.I FriCAS
is an advanced computer algebra system.

.B efricas
starts FriCAS inside Emacs

.B fricas
starts FriCAS using command line interface.
.B fricas
has the following options:
.TP
[-nosman]
use plain command line interface (disables other options).
This option is mandatory when
.I FriCAS
takes input from a pipe
.TP
[-ht|-noht]       whether to use HyperDoc
.TP
[-gr|-nogr]       whether to use Graphics
.TP
[-clef |-noclef]  whether to use Clef
.TP
[-iw|-noiw]       start in interpreter window
.TP
[-ihere|-noihere]
start an interpreter buffer in the original window.
.TP
[-nox]
don't use X Windows
.TP
[-go|-nogo]        whether to start system
.TP
[-ws wsname]
use named workspace
.TP
[-list]
list workspaces only
.TP
[-clefprog fname]
use named program for Clef (command line editing)
.TP
[-h]
show usage
.TP
[-eval code]
evaluate specified code at start
.TP
[-texmacs]
setup FriCAS for communication in TeXmacs protocol
.TP
[-emacs]
setup for emacs frontend
.PP

.SH "SEE ALSO"
The full documentation for
.B fricas
is maintained as a set of HyperDoc pages.  If
.B fricas
is stared inside X Windows environment by default HyperDoc
window will pop up on the screen giving access to complete
documentation.
.SH "BUGS"
Piping data to
.I FriCAS
does not work without '-nosman' option
