#!/bin/sh -e

function fail() {
  echo $@
  exit 1
}

unalias -a

ROOT=`pwd`
CURL="curl -L -O -#"

XCRUN=`which xcrun`
[ -x "$XCRUN" ] ||  \
	fail "You need to install Xcode"

MACOSXSDK=$($XCRUN -sdk macosx -show-sdk-path)
MACOSXVER=${2:-$($XCRUN -sdk macosx -show-sdk-version)}
ARCH=`uname -m`

SRCDIR=`cd ${ROOT}/../..; pwd`

if [ "$ARCH" = "arm64" ]; then
	SBCLVER="2.1.2"
else
	SBCLVER="2.2.9"
fi
SBCLTBZ="sbcl-${SBCLVER}-${ARCH}-darwin-binary.tar.bz2"
SBCLDIR="sbcl-${SBCLVER}-${ARCH}-darwin"

[ -f "${SRCDIR}/contrib/macos/mk_app" ] || \
  fail "Please start the command in 'contrib/macos' directory."

[ -d "${MACOSXSDK}" ] || \
  fail "No MacOSX SDK installed: please install Xcode"

FRICASVER=`sed -n 's#.*\[FriCAS\], \[\(.*\)\],#\1#p' "${SRCDIR}/configure.ac"`

[ -n "${FRICASVER}" ] || \
  fail "Cannot extract FriCAS version number from sources."

export CC="clang -isysroot ${MACOSXSDK} -mmacosx-version-min=${MACOSXVER} -arch ${ARCH}"

action=${1:-build}

if [ "${action}" == "build" ]; then
  if [ ! -f ${SBCLTBZ} ]; then
    echo "Downloading ${SBCLTBZ}:"
    ${CURL} "http://downloads.sf.net/sourceforge/sbcl/${SBCLVER}/${SBCLTBZ}"
  fi

  [ -d ${SBCLDIR} ] || tar xvjf ${SBCLTBZ}

  export LC_ALL=C
  export LANG=C

  rm -rf FriCAS.app
  mkdir -p FriCAS.app/Contents/{MacOS,Resources}

  mkdir -p build
  pushd build
  ${SRCDIR}/configure \
    --prefix="" \
    --with-lisp="${ROOT}/${SBCLDIR}/run-sbcl.sh"
  make
  make DESTDIR=${ROOT}/FriCAS.app/Contents/Resources install
  popd

  sed -e "s,FRICASVER,${FRICASVER}," \
      Info.plist > ${ROOT}/FriCAS.app/Contents/Info.plist

  ${CC} -O2 -Wall -framework CoreFoundation FriCAS.c \
    -o FriCAS.app/Contents/MacOS/FriCAS

  install appIcon.icns FriCAS.app/Contents/Resources/
fi

if [ "${action}" == "dist" ]; then

  [ -d FriCAS.app ] || fail "Build the app first with $0 build"
  [ -f FriCAS.dmg ] && rm FriCAS.dmg

  mkdir -p dmg
  mv FriCAS.app dmg
  chmod +x create_dmg 2>/dev/null
  ./create_dmg \
	  --no-internet-enable \
	  --volname FriCAS \
	  --background fricas_dmg_background.png \
	  --volicon appIcon.icns \
	  --window-pos 200 120 \
	  --window-size 500 320 \
	  --icon-size 80 \
	  --icon FriCAS.app 130 155 \
	  --hide-extension FriCAS.app \
	  --app-drop-link 375 155 \
	  FriCAS.dmg dmg \
	  || fail "Error building DMG - manual cleanup is probably necessary"
  mv dmg/FriCAS.app .
  rmdir dmg
fi

if [ "${action}" == "clean" ]; then
  rm -vrf ${SBCLDIR}
  rm -vrf FriCAS.app
  rm -vrf FriCAS.dmg
  rm -vrf build
  rm -vf *~
fi
