#!/bin/sh -e

function fail() {
  echo $@
  exit 1
}

unalias -a

ROOT=`pwd`
CURL="curl -L -O -#"

XCRUN=`which xcrun`
[ -x "$XCRUN" ] ||  \
	fail "You need to install Xcode"

MACOSXSDK=$($XCRUN -sdk macosx -show-sdk-path)
MACOSXVER=${2:-$($XCRUN -sdk macosx -show-sdk-version)}
ARCH=`uname -m`

SRCDIR=`cd ${ROOT}/../..; pwd`

if [ "$ARCH" = "arm64" ]; then
	SBCLVER="2.1.2"
else
	SBCLVER="2.2.9"
fi
SBCLTBZ="sbcl-${SBCLVER}-${ARCH}-darwin-binary.tar.bz2"
SBCLDIR="sbcl-${SBCLVER}-${ARCH}-darwin"

[ -f "${SRCDIR}/contrib/macos/mk_app" ] || \
  fail "Please start the command in 'contrib/macos' directory."

[ -d "${MACOSXSDK}" ] || \
  fail "No MacOSX SDK installed: please install Xcode"

FRICASVER=`sed -n 's#.*\[FriCAS\], \[\(.*\)\],#\1#p' "${SRCDIR}/configure.ac"`

[ -n "${FRICASVER}" ] || \
  fail "Cannot extract FriCAS version number from sources."

export CC="clang -isysroot ${MACOSXSDK} -mmacosx-version-min=${MACOSXVER} -arch ${ARCH}"

action=${1:-build}

if [ "${action}" == "build" ]; then
  if [ ! -f ${SBCLTBZ} ]; then
    echo "Downloading ${SBCLTBZ}:"
    ${CURL} "http://downloads.sf.net/sourceforge/sbcl/${SBCLVER}/${SBCLTBZ}"
  fi

  [ -d ${SBCLDIR} ] || tar xvjf ${SBCLTBZ}

  export LC_ALL=C
  export LANG=C

  rm -rf FriCAS.app
  mkdir -p FriCAS.app/Contents/{MacOS,Resources}

  mkdir -p build
  pushd build
  ${SRCDIR}/configure \
    --prefix="" \
    --with-lisp="${ROOT}/${SBCLDIR}/run-sbcl.sh"
  make
  make DESTDIR=${ROOT}/FriCAS.app/Contents/Resources install
  popd

  sed -e "s,FRICASVER,${FRICASVER}," \
      -e "s,MACOSXVER,${MACOSXVER}.0," \
      Info.plist > ${ROOT}/FriCAS.app/Contents/Info.plist

  ${CC} -O2 -Wall -framework CoreFoundation FriCAS.c \
    -o FriCAS.app/Contents/MacOS/FriCAS

  install appIcon.icns FriCAS.app/Contents/Resources/
fi

if [ "${action}" == "dist" ]; then
  tar cvJf FriCAS-${FRICASVER}-${ARCH}-macos${MACOSXVER}.tar.xz FriCAS.app
fi

if [ "${action}" == "clean" ]; then
  rm -vrf ${SBCLDIR}
  rm -vrf FriCAS.app
  rm -vrf build
  rm -vf *~
fi
