#!/bin/sh

htbindir=$FRICAS/lib
htpagedir=$FRICAS/share/hypertex/pages


if test -z "$1"
then
        echo ""|$htbindir/presea use_case=1 -
else
( cd $htpagedir; $htbindir/hthits "$1" $htpagedir/ht.db |sort -r -n -k 1.23 |$htbindir/presea use_case=0 expr="$1" -)
fi
