#!/bin/sh

htbindir=$AXIOM/lib
htpagedir=$AXIOM/share/hypertex/pages


if test -z "$1"
then 
        echo ""|$htbindir/presea case=1 -
else
( cd $htpagedir; $htbindir/hthits "$1" $htpagedir/ht.db |sort -r -n -k 1.22 |$htbindir/presea case=0 expr="$1" -)
fi
