name: Conditional Lisp CI

on: [push, pull_request]
permissions: {}

jobs:
  linux-ccl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'ccl') ||
      contains(github.event.head_commit.message, 'clozure') ||
      contains(github.event.head_commit.message, 'linux')
    uses: ./.github/workflows/linux-ccl.yml

  windows-ccl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'ccl') ||
      contains(github.event.head_commit.message, 'clozure') ||
      contains(github.event.head_commit.message, 'windows')
    uses: ./.github/workflows/windows-ccl.yml

  macOS-ccl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'ccl') ||
      contains(github.event.head_commit.message, 'clozure') ||
      contains(github.event.head_commit.message, 'macos')
    uses: ./.github/workflows/macOS-ccl.yml

  linux-clisp:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'clisp') ||
      contains(github.event.head_commit.message, 'linux')
    uses: ./.github/workflows/linux-clisp.yml

  windows-clisp:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'clisp') ||
      contains(github.event.head_commit.message, 'windows')
    uses: ./.github/workflows/windows-clisp.yml

  macOS-clisp:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'clisp') ||
      contains(github.event.head_commit.message, 'macos')
    uses: ./.github/workflows/macOS-clisp.yml

  linux-ecl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, ' ecl') ||
      contains(github.event.head_commit.message, 'linux')
    uses: ./.github/workflows/linux-ecl.yml

  macOS-ecl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, ' ecl') ||
      contains(github.event.head_commit.message, 'macos')
    uses: ./.github/workflows/macOS-ecl.yml

  linux-gcl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'gcl') ||
      contains(github.event.head_commit.message, 'linux')
    uses: ./.github/workflows/linux-gcl.yml

  linux-cmucl:
    if: >-
      contains(github.event.head_commit.message, 'alllisps') ||
      contains(github.event.head_commit.message, 'cmucl') ||
      contains(github.event.head_commit.message, 'linux')
    uses: ./.github/workflows/linux-cmucl.yml
