name: FriCAS CI on macOS

on: [push, pull_request]
permissions: {}

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      SBCL_VER: ${{ matrix.os == 'macos-15-intel' && '2.2.9' || '2.4.0' }}
      ARCH: ${{ matrix.os == 'macos-15-intel' && 'x86-64' || 'arm64' }}

    steps:
    - uses: actions/checkout@v6

    - name: download and install SBCL
      run: |
        brew install make
        # wget https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VER}/sbcl-${SBCL_VER}-${ARCH}-darwin-binary.tar.bz2
        wget https://github.com/fricas/fricas-nightly-builds/releases/download/build-tools/sbcl-${SBCL_VER}-${ARCH}-darwin-binary.tar.bz2
        tar xvf sbcl-${SBCL_VER}-${ARCH}-darwin-binary.tar.bz2
        cd sbcl-${SBCL_VER}-${ARCH}-darwin && sudo ./install.sh

    - name: configure
      run: |
        mkdir ../build && cd ../build
        ../jlfricas/configure --with-lisp=sbcl --with-gmp=`brew --prefix` || cat config.log

    - name: make
      run: cd ../build && gmake -j4 --output-sync

    - name: Create artifact archives
      run: |
        cd ../build
        make dist-macos
        cp -v `brew list gmp | grep libgmp.10.dylib` FriCAS.app/Contents/Resources/usr/local/lib/fricas/target/*/lib/
        ## reduce chance of error caused by "hdiutil: Resource busy"
        make dist-macos-dmg || make dist-macos-dmg
        mv FriCAS.dmg ../jlfricas/jlFriCAS-macOS-${ARCH}-${{ github.sha }}.dmg

    - name: Upload macOS binary
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: jlFriCAS-macOS-${{ env.ARCH }}-${{ github.sha }}.dmg

    - name: make check
      run: cd ../build && gmake check -j4 --output-sync
