name: FriCAS CI on Windows

on: [push, pull_request]
permissions: {}

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-11-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      SBCL_VER: ${{ matrix.os == 'windows-2022' && '2.3.2' || '2.6.2' }}
      ARCH: ${{ matrix.os == 'windows-2022' && 'x86-64' || 'arm64' }}
      MSYSTEM: ${{ matrix.os == 'windows-2022' && 'UCRT64' || 'CLANGARM64' }}
      INSTALL_PREFIX : ${{ matrix.os == 'windows-2022' && 'mingw-w64-ucrt-x86_64' || 'mingw-w64-clang-aarch64' }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{env.MSYSTEM}}
        install: make ${{env.INSTALL_PREFIX}}-gcc ${{env.INSTALL_PREFIX}}-gmp gmp-devel zip

    - name: download and install SBCL
      run: |
        # wget https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VER}/sbcl-${SBCL_VER}-${ARCH}-windows-binary.msi
        wget https://github.com/fricas/fricas-nightly-builds/releases/download/build-tools/sbcl-${SBCL_VER}-${ARCH}-windows-binary.msi
        msiexec -i sbcl-${SBCL_VER}-${ARCH}-windows-binary.msi -passive

    - uses: actions/checkout@v6

    - name: configure and make
      run: |
        export SBCL_HOME="/c/Program Files/Steel Bank Common Lisp/"
        export PATH="$SBCL_HOME":$PATH
        mkdir ../build && cd ../build
        ../jlfricas/configure --with-lisp=sbcl --enable-gmp || cat config.log
        make -j4 --output-sync

    - name: Create artifact archives
      run: |
        cp -rp ../build/target/*/ jlFriCAS-windows-${ARCH}
        rm jlFriCAS-windows-${ARCH}/bin/fricas
        cp ${MINGW_PREFIX}/bin/libgmp-10.dll jlFriCAS-windows-${ARCH}/lib/
        zip -r jlFriCAS-windows-${ARCH}-${{ github.sha }}.zip jlFriCAS-windows-${ARCH}

    - name: Upload Windows binary
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: jlFriCAS-windows-${{env.ARCH}}-${{ github.sha }}.zip

    - name: make check
      run: cd ../build && make check -j4 --output-sync
